# see https://prettier.io/docs/en/configuration.html
semi: false
printWidth: 80
tabWidth: 4
singleQuote: true
plugins:
    - '@ianvs/prettier-plugin-sort-imports'
importOrder:
    - '.scss$'
    - '^@storybook/react$'
    - '^clsx$'
    - '^react$'
    - '<THIRD_PARTY_MODULES>'
    - '^@/'
    - '^[.]'
