name: Publishing on NPM

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - package.json

permissions:
    contents: read
    id-token: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Build package
              run: |
                  pnpm install
                  pnpm run build

            - name: Publishing on NPM
              uses: JS-DevTools/npm-publish@v3
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  access: public
                  provenance: true
